apiVersion: v1
kind: Service
metadata:
  name: meu-blog-escalavel-service
spec:
  type: LoadBalancer
  selector:
    app: wordpress-escalavel
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
